// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeenIt.Api.Data;

#nullable disable

namespace SeenIt.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914141025_AddUserProfile")]
    partial class AddUserProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("EpisodioAssistido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssistidoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalCharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExternalEpisodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExternalSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeEpisodio")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroEpisodio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersonagemFavoritoNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Temporada")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExternalEpisodeId")
                        .IsUnique();

                    b.ToTable("EpisodiosAssistidos");
                });

            modelBuilder.Entity("SeenIt.Api.Domain.EpisodioAssistidoSentimento", b =>
                {
                    b.Property<Guid>("EpisodioAssistidoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sentimento")
                        .HasColumnType("INTEGER");

                    b.HasKey("EpisodioAssistidoId", "Sentimento");

                    b.ToTable("EpisodiosAssistidosSentimentos");
                });

            modelBuilder.Entity("SeenIt.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarFileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SeenIt.Api.Domain.UserSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalSeriesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExternalSeriesId")
                        .IsUnique();

                    b.ToTable("UserSeries");
                });

            modelBuilder.Entity("EpisodioAssistido", b =>
                {
                    b.HasOne("SeenIt.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeenIt.Api.Domain.EpisodioAssistidoSentimento", b =>
                {
                    b.HasOne("EpisodioAssistido", "EpisodioAssistido")
                        .WithMany("Sentimentos")
                        .HasForeignKey("EpisodioAssistidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EpisodioAssistido");
                });

            modelBuilder.Entity("SeenIt.Api.Domain.UserSeries", b =>
                {
                    b.HasOne("SeenIt.Api.Domain.User", "User")
                        .WithMany("Series")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EpisodioAssistido", b =>
                {
                    b.Navigation("Sentimentos");
                });

            modelBuilder.Entity("SeenIt.Api.Domain.User", b =>
                {
                    b.Navigation("Series");
                });
#pragma warning restore 612, 618
        }
    }
}
